# GENERAL
environment:
  sdk: '>=2.19.0 <3.0.0'

name: vpsd57h3

version: 0.0.0


# GLOBAL
dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.4

  flutter_web_plugins:
    sdk: flutter

  google_fonts: ^4.0.1

  provider: ^6.0.5

  pubnub: ^4.2.2


dev_dependencies:
  pedantic_mono: any


# LOCAL
flutter:
  assets:
    - asset/json/
    - asset/svg/

  uses-material-design: true
